name: Build and Test

on: [push, pull_request]

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_COMMIT_TAG: sha-${{ github.sha }}
  INFRASTRUCTURE_REPO: sies-at/SIES-infrastructure

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      # Setup buildx Runnera
      - name: Buildx Runner Setup
        uses: docker/setup-buildx-action@v2.0.0

      # Login against docker registry if event not PR
      - name: Log into registry ${{ env.IMAGE_REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Extract metadata (tags, labels) for docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=sha,format=long
            type=raw,value={{branch}}-{{sha}}

      # Build and push Docker Image with Buildx (Not on PR)
      - name: Build and push Docker Image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request'}}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
